---
- name: Install nginx with vhosts
  remote_user: runner
  hosts: webservers
  become: true
  become_method: sudo
  gather_facts: no

  vars:
    sites:
    - "fizfak.com"
    - "mehmat.com"
    - "biofak.com"

  roles:
  - nginx-vhosts
